student_count = 19
#first we print the lst of students
puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Ben Hutchinson"
puts "Rich Lake"
puts "Chris Handley"
puts "Izzy Markwick"
puts "Nick Dyer"
puts "Alex Blease"
puts "Giogia Amici"
puts "Christopher Batts"
puts "Dale Stevens"
puts "Edward Byne"
puts "Alan Bridger"
puts "Tim Scully"
puts "Mishal L"
puts "Pavel Redics"
puts "Simon Lange"
puts "Clare Trembath"
puts "Claudia B"
puts "Ayo Obembe"
puts "Benjam Conway"
#finally, we print the total number of students
puts "Overall, we have #{student_count} great students"

